name: 创建一个 Taroify 的 Issue
description: 如果有什么事情不像预期的那样工作，请告诉我们
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您的反馈！
        在提交问题之前，请确保您使用的是所有最新版本 @taroify/* 包。
  - type: dropdown
    id: package
    attributes:
      label: 问题出在哪个包
      multiple: true
      options:
        - '@taroify/core'
        - '@taroify/icons'
        - '@taroify/hooks'
        - '@taroify/commerce'
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 问题出在哪个平台/设备/浏览器
      multiple: true
      options:
        - 'H5'
        - '微信小程序'
        - '支付宝小程序'
        - '百度小程序'
    validations:
      required: true
  - type: input
    id: user_agent
    attributes:
      label: 平台/设备/浏览器
      description: 在哪些平台/设备/浏览器上能重现这个问题？
  - type: textarea
    id: description
    attributes:
      label: 描述一下您遇到的问题
      placeholder: 比如：弹窗无法展示、日历组件报错
    validations:
      required: true
  - type: textarea
    id: reproduce_steps
    attributes:
      label: 重现步骤
      description: 请提供一个最简单的操作步骤，方便我们快速重现问题。
      placeholder: |
        比如：
        1. 点击按钮
        2. 弹窗无法展示
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: 如果可能的话，请包含一个代码框的链接与复制的问题
      description: Codesandbox template – https://codesandbox.io/s/mantine-template-9ze89
  - type: dropdown
    id: fix
    attributes:
      label: 你知道如何解决这个问题吗
      options:
        - 'Yes'
        - 'No'
  - type: dropdown
    id: participate
    attributes:
      label: 您是否愿意参与修复这个问题，并创建一个 PR
      options:
        - 'Yes'
        - 'No'
  - type: textarea
    id: possible_fix
    attributes:
      label: Possible fix
